services:
    apache:
        image: tugboatqa/httpd
        aliases:
            - test1-1
            - test2-1
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            build: cat .tugboat/tugboat.txt
