services:
    php:
        image: tugboatqa/php:apache
        http: true
        https: false
        commands:
            init:
                - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"

        visualdiffs:
            :default:
                - /
            foo:
                - /
            bar:
                - /
