services:
    nginx:
        image: tugboatqa/nginx
        default: true
        commands:
            init:
                - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
                - cp .tugboat/default.conf /etc/nginx/conf.d/default.conf

    php:
        image: tugboatqa/php:fpm
        checkout: true

