services:
    apache:
        image: tugboatqa/php:apache
        aliases: test
        http: true
        https: false
        commands:
            init:
                - echo "********** INIT **********"
                - apt-get update
                - apt-get install bsd-mailx
                - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
                - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            update:
                - echo "********** UPDATE **********"
            build:
                - echo "********** BUILD **********"
                - cat .tugboat/tugboat.txt
