services:
    apache:
        image: tugboatqa/httpd
        aliases: test
        http: true
        https: false
        depends: memcached
        default: true
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            build: echo $TUGBOAT_SERVICE
    memcached:
        image: tugboatqa/memcached
        depends: redis
        commands:
            build: echo $TUGBOAT_SERVICE
    redis:
        image: tugboatqa/redis
        commands:
            build: echo $TUGBOAT_SERVICE
    varnish:
        image: tugboatqa/varnish
        depends: apache
        commands:
            build: echo $TUGBOAT_SERVICE
