services:
  apache:
    image: tugboatqa/alpine
    aliases: test
    http: true
    https: false
    expose: 8080
    commands:
      init:
        - apk add --no-cache --virtual .build-deps bash gcc musl-dev openssl go
        - wget -O go.tgz https://dl.google.com/go/go1.24.1.src.tar.gz
        - tar -C /usr/local -xzf go.tgz
        - cd ${TUGBOAT_ROOT}/server && go mod download
        - cd ${TUGBOAT_ROOT}/server && go build -o server .
      start:
        - cd ${TUGBOAT_ROOT}/server && ./server &
