services:
    apache:
        image: tugboatqa/httpd
        aliases: test
        http: true
        https: false
        commands:
            init:
                - echo "********** INIT **********"
                - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            update:
                - echo "********** UPDATE **********"
            build:
                - echo "********** BUILD **********"
            online:
                - echo "********** ONLINE **********"
                - curl $TUGBOAT_DEFAULT_SERVICE_URL
