services:
    apache:
        image: tugboatqa/httpd
        aliases: test
        http: true
        https: false
        commands:
            init:
                - apt-get update
                - apt-get install bsd-mailx
                - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
                - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            build:
                - cat .tugboat/tugboat.txt | mail -s "[1] Tugboat Preview ${TUGBOAT_PREVIEW_ID}" tugboat@example.com
                - cat .tugboat/tugboat.txt | mail -s "[2] Tugboat Preview ${TUGBOAT_PREVIEW_ID}" tugboat@example.com
                - cat .tugboat/tugboat.txt

                - echo "building for 180 minutes"
                - for x in `seq -w 1 180`; do echo -n $x; date; sleep 60; done
