services:
    apache:
        image: tugboatqa/httpd
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
        screenshots:
            - /
            - /foo:
                aliases: ['bar', 'baz']
                options:
                    timeout: 30
                    waitUntil: load
                    retry: 1
            - /burt:
                aliases: ['gumma', 'goo']
                options:
                    timeout: 45
                    waitUntil: networkidle0
                    retry: 3
