services:
    apache:
        image: tugboatqa/httpd
        default: true
        aliases: test
        http: true
        https: false
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            build: cat .tugboat/tugboat.txt

    memcached:
        image: tugboatqa/memcached

    redis:
        image: tugboatqa/redis
