services:
    apache:
        image: tugboatqa/httpd
        default: true
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
        visualdiffs: /
    mysql:
        image: tugboatqa/mysql:5
