services:
    apache:
        image: tugboatqa/httpd
        subpath: true
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            build: cat .tugboat/tugboat.txt
    mysql:
        image: tugboatqa/mysql
        commands:
        init:
            - scp example.com/database.sql.gz /tmp/
            - zcat /tmp/database.sql.gz | mysql tugboat
            - rm /tmp/database.sql.gz
