services:
    apache:
        image: tugboatqa/php:apache
        aliases: test
        http: true
        https: false
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            build: cat .tugboat/tugboat.txt
