services:
    apache:
        image: tugboatqa/httpd
        aliases: test
        http: true
        https: false
        commands:
            init:
                - apt-get update
                - apt-get install bsd-mailx
                - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            build:
                - cat .tugboat/tugboat.txt | mail -s "Tugboat Preview ${TUGBOAT_PREVIEW_ID}" tugboat@example.com
                - cat .tugboat/tugboat.txt
