services:
    apache:
        image: tugboatqa/httpd
        default: true
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
        visualdiffs:
            - url: /
              aliases: [ :default, foo, bar, baz ]
            - /foo
            - /bar
            - /baz
    mysql:
        image: tugboatqa/mysql:5
