services:
    php:
        image: tugboatqa/php:fpm
        default: true
        commands:
            init:
                # Install nginx
                - apt-get update
                - apt-get install nginx

                # Configure nginx
                - ln -snf "${TUGBOAT_ROOT}" /usr/share/nginx/html
                - cp .tugboat/nginx.conf /etc/nginx/conf.d/default.conf

                # Create/Start nginx service
                - mkdir -p /etc/service/nginx
                - cp .tugboat/nginx.run /etc/service/nginx/run
                - chmod +x /etc/service/nginx/run

