services:
    apache:
        image: tugboatqa/httpd
        aliases: test
        http: true
        https: false
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
        visualdiffs:
            - url: /
              waitUntil: ['load', 'networkidle0']
