services:
    apache:
        image: tugboatqa/httpd
        http: true
        https: false
        default: true
        commands:
            init:
                - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
    postgres:
        image: tugboatqa/postgres
