services:
    apache:
        image: tugboatqa/httpd
        default: true
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
        visualdiffs:
            - url: /
              aliases: [ :default, foo, bar ]
            - /foo
            - /bar
    mysql:
        image: tugboatqa/mysql:5
