services:
    apache:
        image: tugboatqa/httpd
        http: true
        https: false
        commands:
            init:
                - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
                - sed -i 's/AllowOverride None/AllowOverride All/g' /usr/local/apache2/conf/httpd.conf
            build:
                - cat .tugboat/tugboat.txt
