services:
  apache:
    image: tugboatqa/alpine
    aliases: test
    http: true
    https: false
    expose: 8080
    commands:
      init:
        - echo "********** INIT **********"
        - apk add --no-cache --virtual .build-deps bash gcc musl-dev openssl go
        - apk add --no-cache runit
        - mkdir -p /etc/service/server
        - cp "${TUGBOAT_ROOT}/.tugboat/runit/server/run" /etc/service/server/run
      update:
        - chmod +x /etc/service/server/run      
      build:
        - echo "********** BUILD **********"
      start:
        - exec runsvdir /etc/service
