services:
    php:
        image: tugboatqa/php:apache
        http: true
        https: false
        commands:
            init:
                - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"

        visualdiffs:
            :default:
              - /
            alias0:
              - /
            alias1:
              - /
            alias2:
              - /
            alias3:
              - /
            alias4:
              - /
            alias5:
              - /
            alias6:
              - /
            alias7:
              - /
            alias8:
              - /
            alias9:
              - /
            alias10:
              - /
            alias11:
              - /
            alias12:
              - /
            alias13:
              - /
            alias14:
              - /
            alias15:
              - /
            alias16:
              - /
            alias17:
              - /
            alias18:
              - /
            alias19:
              - /
            alias20:
              - /
            alias21:
              - /
            alias22:
              - /
            alias23:
              - /
            alias24:
              - /
            alias25:
              - /
            alias26:
              - /
            alias27:
              - /
            alias28:
              - /
            alias29:
              - /
            alias30:
              - /
            alias31:
              - /
            alias32:
              - /
            alias33:
              - /
            alias34:
              - /
            alias35:
              - /
            alias36:
              - /
            alias37:
              - /
            alias38:
              - /
            alias39:
              - /
            alias40:
              - /
            alias41:
              - /
            alias42:
              - /
            alias43:
              - /
            alias44:
              - /
            alias45:
              - /
            alias46:
              - /
            alias47:
              - /
            alias48:
              - /
            alias49:
              - /
