services:
    apache:
        image: tugboatqa/httpd
        default: true
        aliases: test
        http: true
        https: false
        depends: memcached
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            build: echo "##########  apache commands  ##########"

    memcached:
        image: tugboatqa/memcached
        commands:
            build: echo "##########  memcached commands  ##########"

    redis:
        image: tugboatqa/redis
        commands:
            build: echo "##########  redis commands  ##########"
