services:
    apache:
        image: tugboatqa/httpd
        aliases: test
        http: true
        https: false
        commands:
            init:
                - echo "********** INIT **********"
                - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            update:
                - echo "********** UPDATE **********"
            build:
                - echo "********** BUILD **********"
            start:
                - echo "********** START **********"
            online::
                - echo "********** ONLINE *********"

        lighthouse:
            enabled: true
            config:
                foo: bar

        urls: /
