services:
    apache:
        image: tugboatqa/httpd
        default: true
        subpath: true
        commands:
            init: ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
            build: cat .tugboat/tugboat.txt
    mysql:
        image: tugboatqa/mysql
