services:
  apache:
    image: tugboatqa/httpd
    aliases: test
    http: true
    https: false
    visualdiff:
      # Visual Diffs depend on Screenshots being enabled. If Screenshots
      # are disabled for this Service, Visual Diffs are also disabled,
      # and this setting has no effect.
      enabled: true
      # The following options are used when taking a screenshot of
      # the URL for the _base_ preview
      timeout: 30
      waitUntil:
        - networkidle0
      fullPage: true
    urls:
      - /
    commands:
      init:
        - echo "********** INIT **********"
        - apt-get update
        - apt-get install bsd-mailx
        - rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
        - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
      update:
        - echo "********** UPDATE **********"
      build:
        - echo "********** BUILD **********"
        - cat .tugboat/tugboat.txt | mail -s "[1] Tugboat Preview ${TUGBOAT_PREVIEW_ID}" tugboat@example.com
        - cat .tugboat/tugboat.txt | mail -s "[2] Tugboat Preview ${TUGBOAT_PREVIEW_ID}" tugboat@example.com
        - cat .tugboat/tugboat.txt
