services:
  apache:
    image: tugboatqa/alpine
    aliases: test
    http: true
    https: false
    expose: 8080
    commands:
      init:
        - echo "********** INIT **********"
        - apk add --no-cache --virtual .build-deps bash gcc musl-dev openssl go
        - apk add --no-cache runit
        - mkdir -p /etc/service
        - cp -r "${TUGBOAT_ROOT}/.tugboat/runit/server" /etc/service/
        - chmod +x /etc/service/server/run
      update:
        - cd "${TUGBOAT_ROOT}/server" &&  go build -o server main.go && chmod +x server
      build:
        - echo "********** BUILD **********"
        - exec runsvdir /etc/service
